resources:
  containers:
  - container: centos
    image: ethomson/libgit2-centos:latest
    volumes:
    - '$(Build.SourcesDirectory)':/src
    - '$(Build.BinariesDirectory)':/build

pool:
  vmImage: 'Ubuntu 16.04'

container: centos

steps:
- script: /src/ci/build.sh
- script: /src/ci/test.sh
- task: publishtestresults@2
  displayName: Publish Test Results
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: 'results_*.xml'
    searchFolder: '$(Build.BinariesDirectory)'
    mergeTestResults: true
