resources:
  containers:
  - container: centos
    image: ethomson/libgit2-centos:latest

pool:
  vmImage: 'Ubuntu 16.04'

container: centos

steps:
- script: $(Build.SourcesDirectory)/ci/build.sh
- script: $(Build.SourcesDirectory)/ci/test.sh
- task: publishtestresults@2
  displayName: Publish Test Results
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: 'results_*.xml'
    searchFolder: '$(Build.BinariesDirectory)'
    mergeTestResults: true
