# These are the steps used for ssh'ing into a remote host to build and test.
steps:
- task: SSH@0
  displayName: 'Create Build Directory'
  inputs:
    sshEndpoint: freebsd
    commands: |
     set -e
     REMOTE_BASEDIR=$(mktemp -d -t build)
     REMOTE_SOURCEDIR="${REMOTE_BASEDIR}/src"
     REMOTE_OUTPUTDIR="${REMOTE_BASEDIR}/build"
     mkdir "${REMOTE_SOURCEDIR}"
     mkdir "${REMOTE_OUTPUTDIR}"
     echo "##vso[task.setvariable variable=Remote.BaseDir]${REMOTE_BASEDIR}"
     echo "##vso[task.setvariable variable=Remote.SourceDir]${REMOTE_SOURCEDIR}"
     echo "##vso[task.setvariable variable=Remote.OutputDir]${REMOTE_OUTPUTDIR}"

- task: CopyFilesOverSSH@0
  displayName: 'Securely copy files to the remote machine'
  inputs:
    sshEndpoint: freebsd
    sourceFolder: '$(Build.SourcesDirectory)'
    targetFolder: '$(Remote.SourceDir)'

- task: SSH@0
  displayName: 'Create Build Directory'
  inputs:
    sshEndpoint: freebsd
    commands: |
     set -e
     cd $(Remote.OutputDir)
     $(Remote.SourceDir)/ci/build.sh
